"""Versioned research register: documented claims are separate from actual probes."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
probes=json.loads((ROOT/'data/raw/probe-results.json').read_text())
by_id={p['id']:p for p in probes}
entries=[]
def add(id,name,status,role,access,auth,key,free,licence,space,time,history,latency,format,programmatic,limits,reliability,fallback,urls):
    entries.append(dict(id=id,name=name,status=status,role=role,public_access=access,
        authentication=auth,api_key=key,free=free,licence=licence,spatial_resolution=space,
        temporal_resolution=time,historical_coverage=history,latency=latency,format=format,
        programmatic_access=programmatic,rate_limits=limits,server_side='Use backend ingestion and cached files; no provider credentials in browser.',
        reliability=reliability,fallback=fallback,references=urls,probe=by_id.get(id),checked_date='2026-09-12'))

add('imerg','NASA GPM IMERG','PLANNED','Rainfall',
    'Metadata public; tested PPS GIS directory returned HTTP 401.',
    'Free PPS registration for tested GIS route; Earthdata login for GES DISC routes.',
    'No paid API key; account credentials required by download route.',
    'NASA precipitation products free; account needed for tested route.',
    'NASA open-data attribution; cite product/version and GPM/IMERG documentation.',
    '0.1 degree grid (~10 km); too coarse for individual mountain gullies.',
    '30 minutes; daily/monthly derivatives.',
    'Retrospective V07 record; exact selected collection and pilot granule completeness not verified.',
    'Early about 4h; Late nominal 14h; Final about 3.5 months (NASA FAQ). Not instant warning data.',
    'HDF5; GIS GeoTIFF; selected NetCDF services.',
    'Documented HTTPS download after registration; adapter not activated.',
    'Route-specific; numerical PPS limit not verified. Use bounded retries/cache.',
    'Official maintained product; anonymous data access failed; no measured service uptime.',
    'Cached Open-Meteo reanalysis for context; explicit synthetic replay for demo.',
    ['https://gpm.nasa.gov/data/imerg','https://registration.pps.eosdis.nasa.gov/registration/'])
add('imd','IMD gridded rainfall','PLANNED','Historical rainfall',
    'Official form HTTP 200. Following its RF25.php POST returned binary bytes on first attempt; full retry timed out.',
    'No login requested by the tested public form.','No key requested.','Public form currently free.',
    'Cite Pai et al. (2014) and IMD; public download is not an unrestricted redistribution licence. Terms require confirmation for redistribution.',
    '0.25 degrees (~25 km).','Daily; annual files.',
    '1901–2025 shown in the inspected form; 2013 download attempted.',
    'Historical batch; not a subhourly operational sensor. Daily service latency not measured.',
    'NetCDF and binary GRD.',
    'Form POST confirmed; first 15 MB captured then intentionally bounded; not a validated complete dataset. No hard-coded guessed file path.',
    'No numeric limit verified; request annual files once and cache.',
    'Official station-gridded product; two attempts had different outcomes. Daily/coarse rainfall cannot resolve cloudburst timing.',
    'Open-Meteo archive; synthetic scenario.',
    ['https://imdpune.gov.in/cmpg/Griddata/Rainfall_25_NetCDF.html','https://imdpune.gov.in/cmpg/Griddata/Rainfall_25_Bin.html'])
add('mosdac','ISRO MOSDAC soil wetness','PLANNED','Soil moisture/context',
    'Catalog/docs public in browser research; direct automated probe timed out.',
    'Approved MOSDAC account required for data downloads per official manual.',
    'Account/session API authentication; independent API-key requirement not verified.',
    'Public catalog; exact product access depends on approved account.',
    'MOSDAC product terms apply; redistribution rights not verified.',
    'Product-dependent. Official agriculture example uses AMSR-2 surface moisture at 10 km; not proof of a current mountain-valid product.',
    'That example is daily with weekly composites; current selected product unverified.',
    'Historical examples available; exact current product archive unverified.',
    'Not verified for a selected product.','Product-dependent HDF/NetCDF and maps; exact payload unverified.',
    'Official download API documented; cannot test authenticated download without an account.',
    'No numeric limit verified.','Access incomplete; snow, ice, rock and relief require product quality-mask screening.',
    'Open-Meteo modeled soil moisture or explicitly synthetic rainfall-correlated moisture.',
    ['https://mosdac.gov.in/downloadapi-manual','https://www.mosdac.gov.in/soil-moisture','https://mosdac.gov.in/external/agriculture?language=en'])
add('copernicus','Copernicus DEM GLO-30','VERIFIED LIVE','Static terrain downloaded; derived basin bundled',
    'Anonymous S3 listing and both N30 E078/E079 terrain GeoTIFF downloads succeeded.',
    'None on tested public S3 mirror.','None.','Yes, public tiles.',
    'Copernicus DEM licence; preserve attribution and identify derivatives. See licence linked in mirror readme.',
    '1 arc second (~30m) DSM. Demo analysis explicitly resamples to 120m in EPSG:32644.',
    'Static elevation product, not temporal observations.',
    '2021 release on tested mirror; acquisition epoch differs from replay date.',
    'Not applicable.','Cloud Optimized GeoTIFF.',
    'Anonymous HTTPS; object keys resolved from actual bucket listing.',
    'No product-specific numeric limit verified; cache tile downloads and use COG windows.',
    'Two complete downloaded tiles with SHA256. DSM vegetation/buildings and coarse conditioning affect flow paths.',
    'Cached tiles; future HydroSHEDS/MERIT cross-check. OpenTopography needs a free account key if used.',
    ['https://registry.opendata.aws/copernicus-dem/','https://copernicus-dem-30m.s3.amazonaws.com/readme.html'])
add('wris','India-WRIS / CWC water observations','PLANNED','Water level / streamflow',
    'India-WRIS public portal timed out; no stable public observation endpoint verified.',
    'Unverified for station time series.','Unverified; no private credentials available.',
    'Public portal exists; station-series access and terms unverified.',
    'Government source-specific terms; do not assume all hydrological observations are unrestricted.',
    'Point stations; locations and completeness vary.','Unverified for Mandakini observations.',
    'No continuous Mandakini gauge history obtained.','Not measured.','Portal data/exports; exact observation schema not verified.',
    'No observation API activated; provider interface raises an explicit PLANNED error.',
    'Unknown.','Bounded reachability attempt failed. Station inventory does not prove telemetry access.',
    'Synthetic water level explicitly MOCKED within REPLAY; request CWC station archive later.',
    ['https://indiawris.gov.in/wris/','https://www.cwc.gov.in/sites/default/files/meteorological-network-details-of-cwc.pdf'])
add('cwc','CWC station inventory','VERIFIED LIVE','Station metadata only',
    'Official PDF downloaded, HTTP 200.','None for inventory.','None.','Yes, public PDF.',
    'Cite CWC; public report access does not establish a licence for gauge data.',
    'Point coordinates. Chandrapuri rainfall inventory: 30°25′51″N, 79°04′09″E.',
    'Static inventory.','Inventory lists establishment date, not retrieved observations.',
    'Not applicable.','PDF.','HTTP download verified; station extraction/manual review.',
    'No numeric limit verified.','Official metadata; no uptime or gauge calibration evidence collected.',
    'Keep observation provider PLANNED.',
    ['https://www.cwc.gov.in/sites/default/files/meteorological-network-details-of-cwc.pdf'])
add('sentinel1','Sentinel-1 radar','PLANNED','Historical inundation validation candidate',
    'Anonymous spatial catalog query returned one intersecting product; raster not downloaded.',
    'Catalog search anonymous; CDSE account/token for normal product download.',
    'OAuth access token; no paid key required for standard free access.',
    'Standard data access within free quotas.',
    'Copernicus Sentinel free/open data terms with attribution; processing-service quotas separate.',
    'Product-dependent; common IW GRD pixel spacing ~10m does not equal independent ground resolution.',
    'Satellite acquisitions, not a continuous gauge; revisit varies by acquisition plan and satellite availability.',
    'Since 2014 mission era; cannot reconstruct June 2013 with Sentinel-1.',
    'Acquisition/delivery dependent; no pilot acquisition latency measured.',
    'SAFE products containing TIFF and XML.',
    'OData catalog tested; authenticated download, calibration, terrain correction and quality masking PLANNED.',
    'CDSE published general quota: 4 concurrent IAD downloads, 12 TB rolling 30-day transfer before reduced speed; recheck before use.',
    'Catalog reachable. Mountain radar shadow/layover and narrow valleys limit inundation interpretation.',
    'NRSC/government event maps; no fabricated inundation masks.',
    ['https://documentation.dataspace.copernicus.eu/APIs/OData.html','https://documentation.dataspace.copernicus.eu/Quotas.html'])
add('jrc','JRC Global Surface Water','PLANNED','Static surface-water context',
    'Download page HTTP 200; raster tile not yet downloaded.','None for public download; Earth Engine route requires account.','None for direct TIFF.','Yes.',
    'Copernicus terms; attribution Source: EC JRC/Google; cite Pekel et al. (2016).',
    '30m Landsat-derived mapping.','Monthly/yearly histories and multiyear summaries.',
    'Official page updated 26 Aug 2026 reports 1984–2024; v1.5 mixes Landsat collections.',
    'Retrospective; not real-time flood detection.','GeoTIFF, Earth Engine assets, map services.',
    'Official downloadable file list and scripts exist; pixel ingestion PLANNED.',
    'No direct-download numeric limit verified; Earth Engine quotas are separate.',
    'Portal reachable; new release warns about co-registration offsets. Narrow rivers/clouds limit inference.',
    'OSM river geometry for demonstrator; no claim of observed inundation.',
    ['https://global-surface-water.appspot.com/download','https://global-surface-water.appspot.com/faq'])
add('osm','OpenStreetMap','VERIFIED LIVE','Settlements, rivers, bridges, roads and mapped hospitals',
    'One bounded Overpass request succeeded, 1,885 elements; local extract saved.',
    'None for tested read-only Overpass request.','None.','Yes, shared public service.',
    '© OpenStreetMap contributors, ODbL; attribution and derivative database obligations apply.',
    'Vector features; accuracy and completeness variable, not a fixed grid.',
    'Continuously edited map; cached retrieval timestamp in probe log.',
    'Current extract only; not asserted to reconstruct 2013 infrastructure.',
    'Replication-dependent; local extract is not continually live.',
    'Overpass JSON, converted to GeoJSON.',
    'Documented Overpass interpreter query; cached for backend/PostGIS; dashboard does not query Overpass.',
    'Shared-service policy: regular clients should stay below ~100 requests and 10 MB/day; respect 429/backoff and current policy.',
    'Probe succeeded; incomplete infrastructure mapping. Population counts left unknown.',
    'Cached extract; authoritative government inventory after access/terms verification.',
    ['https://wiki.openstreetmap.org/wiki/Overpass_API','https://www.openstreetmap.org/copyright'])
add('reports','Government disaster reports','VERIFIED LIVE','Hand-curated event context, not training truth',
    'NIDM India Disaster Report 2013 downloaded; related official event sources cited in CSV.',
    'None for tested report.','None.','Public reports.',
    'Cite issuing agency and report. Do not assume unrestricted report reproduction.',
    'Narrative locations/maps; no uniform footprint or event-label precision.',
    'Event dates; timing uncertainty retained.','2013 episodes and 2021 Chamoli context in curated CSV.',
    'Retrospective.','PDF; curated CSV references.',
    'PDF download succeeds; labels manually curated, not an invented API.',
    'No numeric limit verified; cache downloads.',
    'Primary agency reports; sparse events do not support skill estimation. 2021 mechanism differs from rainfall flooding.',
    'Replay scenario with its own synthetic target; no measured accuracy.',
    ['https://nidm.gov.in/PDF/pubs/India%20Disaster%20Report%202013.pdf','https://nidm.gov.in/pdf/trgReports/2021/July/Report_26July2021sp.pdf'])
add('openmeteo','Open-Meteo forecast','VERIFIED LIVE','Fallback modeled rainfall/soil sample only',
    'Actual precipitation and soil-moisture JSON returned HTTP 200.','None on free endpoint.','None on free endpoint.',
    'Free endpoint for noncommercial evaluation; commercial access requires paid plan.',
    'Weather data CC BY 4.0, credit Open-Meteo/model providers; hosted API usage terms separate.',
    'Model-dependent, often kilometres; grid output not an IoT station.',
    'Hourly values from forecast model cycles.','Forecast horizon; archive is separate.',
    'Model-cycle dependent; local retrieval succeeded, end-to-end observation latency not measured.',
    'JSON.','Documented HTTP API verified; not automatically substituted into replay.',
    'Free: 600/min, 5,000/hour, 10,000/day, 300,000/month per published pricing.',
    'No free-tier uptime guarantee. Mountain representativeness requires validation.',
    'Cached archive or explicit synthetic provider.',
    ['https://open-meteo.com/en/docs','https://open-meteo.com/en/pricing'])
add('openmeteo_archive','Open-Meteo historical reanalysis','REPLAY','Real cached 2013 weather context',
    '120 hourly values for 14–18 June 2013 downloaded at Kedarnath grid point.',
    'None on tested free endpoint.','None.','Noncommercial free API terms apply.',
    'CC BY 4.0 data attribution; service terms as above.',
    'Reanalysis/model grid, not local ground observation.','Hourly.',
    'Service documents history from 1940; only 2013 pilot sample fetched.',
    'Retrospective, unavailable as issued at the historical event time; not used to claim lead time.',
    'JSON.','Actual archive request verified and cached; replay adapter only emits Kedarnath, never invented neighboring stations.',
    'Shared Open-Meteo limits; query complexity affects accounting.',
    'Accessible context, not independent flood labels or operational forecast validation.',
    'SyntheticReplay with synthetic=true.',
    ['https://open-meteo.com/en/docs/historical-weather-api','https://open-meteo.com/en/pricing'])

(ROOT/'data/source-registry.json').write_text(json.dumps(entries,ensure_ascii=False,indent=2),encoding='utf8')
lines=['# Data source investigation','',
 'Checked 12 September 2026 local time (raw probes use UTC). VERIFIED LIVE means a specified endpoint/payload was actually reached during investigation; it does not mean the dashboard is receiving live sensor observations. Static samples remain static. PLANNED means the required usable product integration is not active. REPLAY identifies cached or simulated temporal playback. MOCKED identifies generated values/models.','',
 'No source has a measured uptime guarantee from this short investigation. Unknown means unverified, not unrestricted. Runtime sources and input provenance remain explicit.','']
for e in entries:
    lines += [f"## {e['name']} — {e['status']}",'']
    for key,value in e.items():
        if key in ('id','name','status','references','probe'): continue
        lines.append(f'- **{key.replace("_"," ")}**: {value}')
    lines+=['','Sources: '+', '.join(f'[Official reference {i+1}]({url})' for i,url in enumerate(e['references'])), '']
    if e['probe']: lines += ['Probe: `'+json.dumps(e['probe'],ensure_ascii=False)+'`','']
(ROOT/'docs').mkdir(exist_ok=True)
(ROOT/'docs/SOURCES.md').write_text('\n'.join(lines),encoding='utf8')
